### ISSUE TITLE
Importing existing projects

### ISSUE THREAD

**Issue by fnagel** [tommy-muehle/puppet-typo3#2]
As already mentioned I would love to have a importing feature for existing projects via SSH.

Something like:
* copy _fileadmin, typo3conf, uploads_ folders
* Importing DB (MySQL only on first step)

Some more ideas:
* adjust _baseUrl_ TS config
* adjust domain record

**Comment by tommy-muehle** [comment]
This issue was moved to move-elevator/puppet-typo3#4
